@host=http://localhost:5166

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIERvZSIsImdpdmVuX25hbWUiOiJKb2huIiwiZmFtaWx5X25hbWUiOiJEb2UiLCJqdGkiOiJkYzkyMGZkYi04ZmYzLTRjZDYtYTBiOC0xYzBhNWY4NmMzMDUiLCJ1bmlxdWVfbmFtZSI6ImU4YzAyN2ZhLTNjMjItNGU0Ni1iZDAxLWM2ODUzMDA3MTY2MiIsImV4cCI6MTcxMzE0MTYxMCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.Lsff6L-QVVSDvyyWEX9sfXSbeOUzWlawi0MCMJkHImQ