@host=http://localhost:5166

POST {{host}}/authentication/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@doe.com",
    "password": "password"
}